spring:
  threads:
    virtual:
      enabled: true # 3.2+

  lifecycle:
    timeout-per-shutdown-phase: 10s

  datasource:
    # TODO: CQRS pattern
    url: jdbc:postgresql://
    username: 1
    password: 1
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: false
      properties:
        hibernate.connection.isolation: 2 # TRANSACTION_READ_COMMITTED
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 123
      password: 123
      username: default
      timeout: 2000ms

server:
  port: 1234

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    csw.youtube.chat: DEBUG

youtube:
  api:
    data-v3-key: AI